// GroupMngScreen.tsx
import React, { useState, useEffect } from 'react';
import { ArrowLeft, Search, Plus, Minus, Users, User as UserIcon, Loader2, ChevronRight, LogOut, Trash2, Bell, 
  Activity, BarChart2, Apple, Stars, Info, ShieldCheck, Dumbbell, FlaskConical, LineChart } from 'lucide-react';
import { writeBatch, collection, query, getDocs, doc, getDoc, addDoc, serverTimestamp, where, updateDoc, collectionGroup, limit, setDoc, deleteField, onSnapshot } from 'firebase/firestore';
import { useNavigate } from 'react-router-dom';
import { auth, db } from '../firebase';
import { useNotifications } from '../context/NotificationContext';
import { type Group, type GroupSearchUser as SearchUser } from './componentsGroupScreen/group';
import aiDoctorImage from '../assets/_aiDoctor.jpg';

const CohortComparison = React.lazy(() => import('./componentsGroupScreen/CohortComparison'));
const Correlation = React.lazy(() => import('./componentsGroupScreen/Correlation'));
const HypothesisTest = React.lazy(() => import('./componentsGroupScreen/HypothesisTest'));


const aiDoctorUid = 'vMnnZIs6xYhVqT9KgTvrnF7Ehvg2'; // Generated by firestore
const RECOMMENDED_MEMBERS: SearchUser[] = [
  { uid: aiDoctorUid, displayName: 'AI Doctor', imageId: aiDoctorImage }
];

const calculateAge = (dobString: string): number => {
  if (!dobString) return 0;
  const today = new Date();
  const birthDate = new Date(dobString);
  let age = today.getFullYear() - birthDate.getFullYear();
  const m = today.getMonth() - birthDate.getMonth();
  if (m < 0 || (m === 0 && today.getDate() < birthDate.getDate())) age--;
  return age;
};

export const GroupMngScreen: React.FC = () => {
  const navigate = useNavigate();
  const { userData, userGroups } = useNotifications();

  const [activeTab, setActiveTab] = useState<'my-groups' | 'create-group' | 'cohort' | 'correlation' | 'hypothesis-test'>('my-groups');
  const [hasStartedCohort, setHasStartedCohort] = useState(false);
  const [hasStartedCorrelation, setHasStartedCorrelation] = useState(false);
  const [hasStartedHypothesis, setHasStartedHypothesis] = useState(false);

  const [groupName, setGroupName] = useState('');
  const [searchQuery, setSearchQuery] = useState('');
  const [searchResults, setSearchResults] = useState<SearchUser[]>([]);
  const [selectedMembers, setSelectedMembers] = useState<SearchUser[]>([]);
  const [isSearching, setIsSearching] = useState(false);
  const [isSearchFocused, setIsSearchFocused] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [optimisticReadIds, setOptimisticReadIds] = useState<Set<string>>(new Set());

  // Profile data for cohort comparison
  const [profileData, setProfileData] = useState<any>(null);
  const [userSex, setUserSex] = useState<string>('');
  const [userAge, setUserAge] = useState<number>(0);

  // Split compare features
  const [enableCompareVitals, setEnableCompareVitals] = useState(false);
  const [enableCompareDiet, setEnableCompareDiet] = useState(false);
  const [enableCompareExercise, setEnableCompareExercise] = useState(false);

  const isLoadingGroups = userGroups === null || userData === null;

  // Fetch user profile data for cohort calculation
  useEffect(() => {
    if (!auth.currentUser) return;
    const profileRef = doc(db, 'users', auth.currentUser.uid, 'profile', 'user_data');
    const unsub = onSnapshot(profileRef, (snap) => {
      if (snap.exists()) {
        const data = snap.data();
        setProfileData(data);
        setUserSex(data.sex || '');
        
        let age = 0;
        if (data.dob) {
          age = calculateAge(data.dob);
        } else if (data.age && Array.isArray(data.age) && data.age.length > 0) {
          age = parseInt(data.age[data.age.length - 1].value);
        }
        setUserAge(age);
      }
    });
    return () => unsub();
  }, []);

  const handleGroupClick = (groupId: string) => {
    setOptimisticReadIds(prev => new Set(prev).add(groupId));    
    if (auth.currentUser) {
      const userRef = doc(db, 'users', auth.currentUser.uid);
      setDoc(userRef, { 
        [`last_read_group_${groupId}`]: serverTimestamp() 
      }, { merge: true }).catch(() => {});
    }
    navigate(`/group/${groupId}`);
  };

  const handleProfileClick = (uid: string) => {
    navigate(`/profile/${uid}`);
  };

  // delete old users/documentId/last_read_group files to update notification
  useEffect(() => {
    if (!auth.currentUser || !userData || !userGroups) return;

    const cleanupOrphanedGroupFields = async () => {
      try {
        const userRef = doc(db, 'users', auth.currentUser!.uid);
        const updates: Record<string, any> = {};
        let needsCleanup = false;

        const lastReadKeys = Object.keys(userData).filter(key => 
          key.startsWith('last_read_group_')
        );

        lastReadKeys.forEach(key => {
          const groupIdFromField = key.replace('last_read_group_', '');
          const isStillMember = userGroups.some((g: Group) => g.id === groupIdFromField);

          if (!isStillMember) {
            updates[key] = deleteField();
            needsCleanup = true;
          }
        });

        if (needsCleanup) {
          await updateDoc(userRef, updates);
          console.log("Successfully scrubbed orphaned group fields.");
        }
      } catch (err) {
        console.error("Error during group field cleanup:", err);
      }
    };

    cleanupOrphanedGroupFields();
  }, [userData, userGroups]); 
  
  // Handle user search
  useEffect(() => {
    const performSearch = async () => {
      if (searchQuery.trim().length < 2) {
        setSearchResults([]);
        return;
      }
      setIsSearching(true);
      try {
        const lowerTerm = searchQuery.toLowerCase();
        
        const q = query(
          collectionGroup(db, 'profile'),
          where('name_lowercase', '>=', lowerTerm),
          where('name_lowercase', '<=', lowerTerm + '\uf8ff'),
          limit(10)
        );
        
        const snapshot = await getDocs(q);
        const results: SearchUser[] = [];

        for (const userDoc of snapshot.docs) {
          const fetchedUserData = userDoc.data();
          const uid = userDoc.ref.parent.parent?.id;
          
          if (!uid || uid === auth.currentUser?.uid || selectedMembers.some(m => m.uid === uid)) continue;
          if (results.some(r => r.uid === uid)) continue;

          let imageId = null;
          try {
            const imgDocRef = doc(db, 'users', uid, 'profile', 'image_data');
            const imgSnap = await getDoc(imgDocRef);
            if (imgSnap.exists()) {
              imageId = imgSnap.data().imageId;
            }
          } catch (imgErr) {
            console.error("Failed to fetch image for user:", uid);
          }

          results.push({
            uid,
            displayName: fetchedUserData.name || fetchedUserData.display_name || 'Unknown User',
            imageId
          });
        }
        setSearchResults(results);
      } catch (error) {
        console.error("Error searching users:", error);
      } finally {
        setIsSearching(false);
      }
    };

    const timer = setTimeout(() => performSearch(), 400);
    return () => clearTimeout(timer);
  }, [searchQuery, selectedMembers]);
  
  const addMember = (user: SearchUser) => {
    setSelectedMembers(prev => [...prev, user]);
    setSearchQuery('');
    setSearchResults([]);
    setIsSearchFocused(false);
  };

  const removeMember = (uid: string) => {
    setSelectedMembers(prev => prev.filter(m => m.uid !== uid));
  };

  const handleSaveGroup = async () => {
    if (!groupName.trim() || selectedMembers.length < 1 || !auth.currentUser) return;
    
    setIsSaving(true);
    try {
      const userDocRef = doc(db, 'users', auth.currentUser.uid);
      const userDocSnap = await getDoc(userDocRef);
      const creatorDisplayName = userDocSnap.exists() 
        ? userDocSnap.data().display_name 
        : (auth.currentUser.displayName || 'New Member');

      const groupData = {
        name: groupName,
        memberUids: [auth.currentUser.uid, ...selectedMembers.map(m => m.uid)],
        members: [
          { userId: auth.currentUser.uid, display_name: creatorDisplayName }, 
          ...selectedMembers.map(m => ({
            userId: m.uid,
            display_name: m.displayName
          }))
        ],
        createdBy: auth.currentUser.uid,
        adminId: auth.currentUser.uid,
        createdAt: serverTimestamp(),
        lastUpdated: serverTimestamp(),
        features: {
          compareExercise: enableCompareExercise,
          compareVitals: enableCompareVitals,
          compareDiet: enableCompareDiet
        }
      };

      await addDoc(collection(db, 'myHealth_groups'), groupData);
      
      setGroupName('');
      setSelectedMembers([]);
      setSearchQuery('');
      setActiveTab('my-groups');
    } catch (error) {
      console.error("Error saving group:", error);
      alert("Failed to create group. Please try again.");
    } finally {
      setIsSaving(false);
    }
  };

  const handleDeleteGroup = async (e: React.MouseEvent, groupId: string) => {
    e.stopPropagation();
    if (window.confirm("Delete this group? This cannot be undone.")) {
      try {
        await purgeGroupData(groupId);
      } catch (error) {
        console.error("Error deleting group:", error);
        alert("Failed to delete group.");
      }
    }
  };

  const handleLeaveGroup = async (e: React.MouseEvent, group: Group) => {
    e.stopPropagation();
    if (!auth.currentUser) return;
    if (window.confirm(`Are you sure you want to leave ${group.name}?`)) {
      try {
        const currentUid = auth.currentUser.uid;
        const updatedMemberUids = group.memberUids.filter(uid => uid !== currentUid);
        const updatedMembers = group.members.filter(m => m.userId !== currentUid);
        if (updatedMemberUids.length === 0) {
          await purgeGroupData(group.id);
        } else {
          const groupRef = doc(db, 'myHealth_groups', group.id);
          const updatePayload: any = {
            memberUids: updatedMemberUids,
            members: updatedMembers
          };
          if (group.adminId === currentUid && updatedMemberUids.length > 0) {
            updatePayload.adminId = updatedMemberUids[0];
          }
          await updateDoc(groupRef, updatePayload);
        }
      } catch (error) {
        console.error("Error leaving group:", error);
        alert("Failed to leave group.");
      }
    }
  };

  const purgeGroupData = async (groupId: string) => {
    const batch = writeBatch(db);
    const groupRef = doc(db, 'myHealth_groups', groupId);
    const messagesRef = collection(db, 'myHealth_groups', groupId, 'messages');
    const messagesSnapshot = await getDocs(messagesRef);
    messagesSnapshot.forEach((msgDoc) => {
      batch.delete(msgDoc.ref);
    });
    batch.delete(groupRef);
    await batch.commit();
  };

  return (
    <div className="max-w-7xl mx-auto p-0 md:p-6 bg-slate-50 min-h-screen pb-20 relative">
      <div className="contents md:flex md:flex-col md:flex-1 md:bg-white md:rounded-3xl md:shadow-sm md:border md:border-slate-100 md:mt-2 md:overflow-hidden">        
        <div className="h-20 md:h-24 border-b border-slate-100 flex items-center shrink-0 bg-white md:rounded-t-3xl">
          <div className="w-20 md:w-24 flex justify-center border-r border-slate-100 h-full items-center">
            <button onClick={() => navigate(-1)} className="flex md:hidden p-2 text-slate-400 hover:text-slate-600 rounded-full transition-colors">
              <ArrowLeft size={28} />
            </button>
          </div>

          <div className="flex-1 px-6 md:px-8 flex flex-col justify-center">
            <h2 className="text-xl md:text-2xl font-black text-slate-800 flex items-center gap-3 tracking-tight">
              {activeTab === 'cohort' ? (
                <><BarChart2 className="text-emerald-500" size={28} /> Cohort Overview</>
              ) : activeTab === 'correlation' ? ( // Add this block
                <><LineChart className="text-emerald-500" size={28} /> Data Correlation</>
              ) : activeTab === 'hypothesis-test' ? (
                <><FlaskConical className="text-emerald-500" size={28} /> Hypothesis Test</>
              ) : activeTab === 'my-groups' ? (
                <><Users className="text-emerald-500" size={28} /> My Groups</>
              ) : (
                <><Plus className="text-emerald-500" size={28} /> Create New Group</>
              )}
            </h2>
          </div>
        </div>

        <div className="flex flex-1 overflow-hidden">
          <div className="w-20 md:w-24 border-r border-slate-100 flex flex-col items-center py-6 gap-6 bg-white shrink-0">

            <button 
              onClick={() => setActiveTab('my-groups')}
              className="flex flex-col items-center gap-1.5 w-full group outline-none"
            >
              <div className={`p-3 rounded-2xl transition-all duration-200 ${
                activeTab === 'my-groups' 
                  ? 'bg-emerald-100 text-emerald-600 shadow-sm' 
                  : 'text-slate-400 group-hover:bg-slate-50'
              }`}>
                <Users size={24} />
              </div>
              <span className={`text-[10px] md:text-xs font-bold text-center ${
                activeTab === 'my-groups' ? 'text-emerald-600' : 'text-slate-500'
              }`}>
                My Groups
              </span>
            </button>

            <button 
              onClick={() => setActiveTab('create-group')}
              className="flex flex-col items-center gap-1.5 w-full group outline-none"
            >
              <div className={`p-3 rounded-2xl transition-all duration-200 ${
                activeTab === 'create-group' 
                  ? 'bg-emerald-100 text-emerald-600 shadow-sm' 
                  : 'text-slate-400 group-hover:bg-slate-50'
              }`}>
                <Plus size={24} />
              </div>
              <span className={`text-[10px] md:text-xs font-bold text-center leading-tight ${
                activeTab === 'create-group' ? 'text-emerald-600' : 'text-slate-500'
              }`}>
                Create<br/>Group
              </span>
            </button>

            {/* Tabs: Cohort & groups buttons */}
            <button 
              onClick={() => setActiveTab('cohort')}
              className="flex flex-col items-center gap-1.5 w-full group outline-none"
            >
              <div className={`p-3 rounded-2xl transition-all duration-200 ${
                activeTab === 'cohort' 
                  ? 'bg-emerald-100 text-emerald-600 shadow-sm' 
                  : 'text-slate-400 group-hover:bg-slate-50'
              }`}>
                <BarChart2 size={24} />
              </div>
              <span className={`text-[10px] md:text-xs font-bold text-center ${
                activeTab === 'cohort' ? 'text-emerald-600' : 'text-slate-500'
              }`}>
                Cohort
              </span>
            </button>

            <button 
              onClick={() => setActiveTab('correlation')}
              className="flex flex-col items-center gap-1.5 w-full group outline-none"
            >
              <div className={`p-3 rounded-2xl transition-all duration-200 ${
                activeTab === 'correlation' 
                  ? 'bg-emerald-100 text-emerald-600 shadow-sm' 
                  : 'text-slate-400 group-hover:bg-slate-50'
              }`}>
                <LineChart size={24} />
              </div>
              <span className={`text-[10px] md:text-xs font-bold text-center ${
                activeTab === 'correlation' ? 'text-emerald-600' : 'text-slate-500'
              }`}>
                Correlation
              </span>
            </button>

            <button 
              onClick={() => setActiveTab('hypothesis-test')}
              className="flex flex-col items-center gap-1.5 w-full group outline-none"
            >
              <div className={`p-3 rounded-2xl transition-all duration-200 ${
                activeTab === 'hypothesis-test' 
                  ? 'bg-emerald-100 text-emerald-600 shadow-sm' 
                  : 'text-slate-400 group-hover:bg-slate-50'
              }`}>
                <FlaskConical size={24} />
              </div>
              <span className={`text-[10px] md:text-xs font-bold text-center leading-tight ${
                activeTab === 'hypothesis-test' ? 'text-emerald-600' : 'text-slate-500'
              }`}>
                Hypothesis<br/>Test
              </span>
            </button>
          </div>

          <div className="flex-1 bg-slate-50/30 overflow-y-auto">

          {/* My Groups, Create Group, Cohort, Hypothesis Test content (explanations) */}
          {activeTab === 'hypothesis-test' ? (
            <div className="p-0 md:p-6 max-w-5xl mx-auto">
              
              {!hasStartedHypothesis ? (
                /* Explanation Screen */
                <div className="bg-white rounded-4xl border border-slate-100 shadow-sm p-8 md:p-12 text-center mt-4 md:mt-0">
                  <div className="w-20 h-20 bg-emerald-50 rounded-3xl flex items-center justify-center text-emerald-500 mx-auto mb-6">
                    <FlaskConical size={40} />
                  </div>
                  <h3 className="text-2xl font-black text-slate-800 mb-4">Hypothesis Testing</h3>
                  <p className="text-slate-600 max-w-lg mx-auto mb-8">
                    Design experiments to test health correlations, such as how calorie intake 
                    thresholds affect your weight gain or identifying potential food contamination 
                    based on vital sign fluctuations.
                  </p>
                  
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-left mb-10">
                    <div className="p-4 border border-slate-100 rounded-2xl bg-slate-50/50">
                      <p className="font-bold text-slate-800 text-sm">Example: Weight Gain</p>
                      <p className="text-xs text-slate-500">"Does exceeding my TDEE by 15% consistently result in weight gain over 14 days?"</p>
                    </div>
                    <div className="p-4 border border-slate-100 rounded-2xl bg-slate-50/50">
                      <p className="font-bold text-slate-800 text-sm">Example: Contamination</p>
                      <p className="text-xs text-slate-500">"Is there a correlation between 'nausea' symptoms and spikes in heart rate after meals?"</p>
                    </div>
                  </div>

                  {/* START BUTTON */}
                  <button 
                    onClick={() => setHasStartedHypothesis(true)}
                    className="group flex items-center justify-center gap-3 bg-slate-900 text-white px-8 py-4 rounded-2xl font-bold hover:bg-emerald-600 transition-all duration-300 shadow-lg shadow-slate-200 hover:shadow-emerald-100 mx-auto"
                  >
                    Start Hypothesis Test
                    <ChevronRight size={20} className="group-hover:translate-x-1 transition-transform" />
                  </button>
                </div>
              ) : (
                /* Actual Component Screen */
                <React.Suspense fallback={
                  <div className="flex flex-col items-center justify-center p-12 text-slate-400">
                    <Loader2 className="animate-spin text-emerald-500 mb-4" size={32} />
                    <span className="font-medium text-sm">Loading Hypothesis Tool...</span>
                  </div>
                }>
                  <HypothesisTest
                    profileData={profileData}
                   />
                </React.Suspense>
              )}
            </div>
          ) : activeTab === 'correlation' ? (
          <div className="p-0 md:p-6 max-w-5xl mx-auto">
            {!hasStartedCorrelation ? (
              <div className="bg-white rounded-4xl border border-slate-100 shadow-sm p-8 md:p-12 text-center mt-4 md:mt-0">
                <div className="w-20 h-20 bg-emerald-50 rounded-3xl flex items-center justify-center text-emerald-500 mx-auto mb-6">
                  <LineChart size={40} />
                </div>
                <h3 className="text-2xl font-black text-slate-800 mb-4">Correlation Analysis</h3>
                <p className="text-slate-600 max-w-lg mx-auto mb-8">
                  Discover relationships between different health metrics. See how your activity 
                  impacts your sleep quality or how diet changes correlate with your heart rate.
                </p>
                
                <button 
                  onClick={() => setHasStartedCorrelation(true)}
                  className="group flex items-center justify-center gap-3 bg-slate-900 text-white px-8 py-4 rounded-2xl font-bold hover:bg-emerald-600 transition-all duration-300 shadow-lg shadow-slate-200 hover:shadow-emerald-100 mx-auto"
                >
                  Explore Correlations
                  <ChevronRight size={20} className="group-hover:translate-x-1 transition-transform" />
                </button>
              </div>
            ) : (
              <React.Suspense fallback={
                <div className="flex flex-col items-center justify-center p-12 text-slate-400">
                  <Loader2 className="animate-spin text-emerald-500 mb-4" size={32} />
                  <span className="font-medium text-sm">Analyzing correlations...</span>
                </div>
              }>
                <Correlation profileData={profileData} />
              </React.Suspense>
            )}
          </div>
          ) : activeTab === 'cohort' ? (
              <div className="p-0 md:p-6 max-w-5xl mx-auto">
                
                {!hasStartedCohort ? (
                  /* Initial explanation screen */
                  <div className="bg-white rounded-4xl border border-slate-100 shadow-sm overflow-hidden mt-4 md:mt-0">
                    <div className="p-8 md:p-12 flex flex-col items-center text-center">
                      <div className="w-20 h-20 bg-emerald-50 rounded-3xl flex items-center justify-center text-emerald-500 mb-6">
                        <BarChart2 size={40} />
                      </div>
                      
                      <h3 className="text-2xl font-black text-slate-800 mb-4">Understanding Cohort Data</h3>
                      
                      <div className="space-y-4 max-w-lg mb-10">
                        <div className="flex items-start gap-4 text-left">
                          <div className="mt-1 bg-blue-50 p-2 rounded-lg text-blue-500"><ShieldCheck size={20}/></div>
                          <p className="text-slate-600 text-sm">
                            <strong>Anonymized Comparison:</strong> Compare your vitals and health metrics against an aggregated group of users in your age bracket and sex.
                          </p>
                        </div>
                        <div className="flex items-start gap-4 text-left">
                          <div className="mt-1 bg-emerald-50 p-2 rounded-lg text-emerald-500"><Info size={20}/></div>
                          <p className="text-slate-600 text-sm">
                            <strong>Personalized Insights:</strong> Calculations are performed in real-time to show where you stand relative to your peer group.
                          </p>
                        </div>
                      </div>

                      <button 
                        onClick={() => setHasStartedCohort(true)}
                        className="group flex items-center gap-3 bg-slate-900 text-white px-8 py-4 rounded-2xl font-bold hover:bg-emerald-600 transition-all duration-300 shadow-lg shadow-slate-200 hover:shadow-emerald-100"
                      >
                        Generate Cohort Analysis
                        <ChevronRight size={20} className="group-hover:translate-x-1 transition-transform" />
                      </button>
                    </div>
                  </div>
                ) : (
                  <>
                    {profileData && userSex && userAge ? (
                      <React.Suspense fallback={
                        <div className="flex flex-col items-center justify-center p-12 text-slate-400">
                          <Loader2 className="animate-spin text-emerald-500 mb-4" size={32} />
                          <span className="font-medium text-sm">Loading Analysis Tools...</span>
                        </div>
                      }>
                        <CohortComparison 
                          userId={auth.currentUser?.uid} 
                          userData={profileData} 
                          userSex={userSex} 
                          userAge={userAge} 
                        />
                      </React.Suspense>
                    ) : !userSex || !userAge ? (
                      <div className="text-center p-12 text-slate-500 bg-white rounded-3xl border border-slate-100 shadow-sm max-w-lg mx-auto mt-10">
                        <Activity size={48} className="mx-auto mb-4 text-slate-200" />
                        <p className="text-lg font-medium text-slate-600">Profile Incomplete</p>
                        <p className="text-sm mt-1 text-slate-400">
                          We need your age and sex to find a matching cohort for comparison.
                        </p>
                        <button 
                          onClick={() => navigate(`/profile/${auth.currentUser?.uid}`)}
                          className="mt-6 px-6 py-2.5 bg-emerald-50 text-emerald-600 font-bold rounded-xl hover:bg-emerald-100 transition-colors"
                        >
                          Update Profile
                        </button>
                      </div>
                    ) : (
                      <div className="flex flex-col items-center justify-center p-12 text-slate-400">
                        <Loader2 className="animate-spin text-emerald-500 mb-4" size={32} />
                        <span className="font-medium text-sm">Loading Cohort Data...</span>
                      </div>
                    )}
                  </>
                )}
              </div>
            ) : activeTab === 'my-groups' ? (
              <div className="p-4 md:p-8">
                {isLoadingGroups ? (
                  <div className="flex justify-center p-12">
                    <Loader2 className="animate-spin text-emerald-500" size={32} />
                  </div>
                ) : userGroups.length === 0 ? (
                  <div className="text-center p-12 text-slate-500 bg-white rounded-3xl border border-slate-100 shadow-sm max-w-lg mx-auto mt-10">
                    <Users size={48} className="mx-auto mb-4 text-slate-200" />
                    <p className="text-lg font-medium text-slate-600">No groups found</p>
                    <p className="text-sm mt-1 text-slate-400">You haven't joined or created any groups yet.</p>
                    <button 
                      onClick={() => setActiveTab('create-group')}
                      className="mt-6 px-6 py-2.5 bg-emerald-50 text-emerald-600 font-bold rounded-xl hover:bg-emerald-100 transition-colors"
                    >
                      Create your first group
                    </button>
                  </div>
                ) : (
                  <div className="grid grid-cols-1 lg:grid-cols-2 gap-4 max-w-5xl">
                    {userGroups.map((group: Group) => {
                      const updatedTime = group.lastUpdated?.toMillis() || 0;
                      // @ts-ignore
                      const readTime = userData?.[`last_read_group_${group.id}`]?.toMillis() || 0;
                      const isOptimisticallyRead = optimisticReadIds.has(group.id);
                      const isUnread = updatedTime > readTime && !isOptimisticallyRead;

                      return (
                        <div 
                          key={group.id}
                          onClick={() => handleGroupClick(group.id)}
                          className={`group p-5 bg-white border rounded-2xl cursor-pointer transition-all flex items-center justify-between ${
                            isUnread 
                              ? 'border-emerald-300 ring-2 ring-emerald-50 shadow-md' 
                              : 'border-slate-200 shadow-sm hover:border-emerald-300 hover:shadow-md'
                          }`}
                        >
                          <div className="flex-1 min-w-0 pr-4">
                            <div className="flex items-center gap-2">
                              {isUnread && (
                                <div className="relative flex shrink-0 items-center justify-center">
                                  <span className="absolute animate-ping inline-flex h-3 w-3 rounded-full bg-emerald-400 opacity-75"></span>
                                  <div className="relative bg-emerald-500 rounded-full p-1 border border-white shadow-sm">
                                    <Bell size={10} className="text-white fill-white" />
                                  </div>
                                </div>
                              )}
                              <h3 className={`truncate text-lg ${isUnread ? 'font-black text-emerald-900' : 'font-bold text-slate-800'}`}>
                                {group.name}
                              </h3>
                            </div>

                            <p className="text-sm text-slate-500 flex items-center gap-1.5 mt-1.5">
                              <Users size={14} className="text-slate-400" /> {group.members.length} Members
                            </p>

                            <div className="flex flex-wrap gap-1.5 mt-3">
                                {group.members.slice(0, 4).map(m => (
                                  <span 
                                    key={m.userId} 
                                    onClick={(e) => { e.stopPropagation(); handleProfileClick(m.userId); }}
                                    className="text-[11px] font-medium bg-slate-100 hover:bg-indigo-50 hover:text-indigo-600 px-2.5 py-1 rounded-full text-slate-600 truncate max-w-25 transition-colors"
                                  >
                                    {m.display_name}
                                  </span>
                                ))}
                                {group.members.length > 4 && <span className="text-[11px] font-medium text-slate-400 py-1">+{group.members.length - 4} more</span>}
                            </div>
                          </div>

                          <div className="flex items-center gap-1 shrink-0">
                            {group.adminId === auth.currentUser?.uid && (
                              <button 
                                onClick={(e) => handleDeleteGroup(e, group.id)} 
                                className="p-2.5 text-rose-400 hover:text-rose-600 hover:bg-rose-50 rounded-full transition-colors md:opacity-0 md:group-hover:opacity-100" 
                                title="Delete Group"
                              >
                                <Trash2 size={20} />
                              </button>
                            )}
                            <button 
                              onClick={(e) => handleLeaveGroup(e, group)} 
                              className="p-2.5 text-slate-400 hover:text-orange-500 hover:bg-orange-50 rounded-full transition-colors md:opacity-0 md:group-hover:opacity-100" 
                              title="Leave Group"
                            >
                              <LogOut size={20} />
                            </button>
                            <ChevronRight className="text-slate-300 group-hover:text-emerald-500 transition-transform group-hover:translate-x-1 ml-1" size={24} />
                          </div>
                        </div>
                      );
                    })}
                  </div>
                )}
              </div>
            ) : (
              <div className="flex justify-center items-start p-4 md:p-8">
                <div className="w-full max-w-2xl flex flex-col bg-white border border-slate-200 shadow-sm rounded-3xl overflow-hidden">
                  
                  <div className="p-6 md:p-8 space-y-8">
                    {/* Input: Group name & features */}
                    <div>
                      <label className="block text-xs font-bold text-slate-400 uppercase tracking-widest mb-3">Group Identity</label>
                      <input 
                        type="text" 
                        placeholder="e.g. Project Alpha" 
                        value={groupName}
                        onChange={(e) => setGroupName(e.target.value)}
                        className="w-full bg-slate-50 border border-slate-200 rounded-2xl px-5 py-4 text-slate-700 text-lg focus:outline-none focus:ring-2 focus:ring-emerald-500/20 focus:border-emerald-500 transition-all"
                      />
                      
                      <div className="mt-4 flex flex-col gap-3 ml-1">
                        <div className="flex items-center gap-3">
                          <input 
                            type="checkbox" 
                            id="vitalsCompareCheck"
                            checked={enableCompareVitals}
                            onChange={(e) => setEnableCompareVitals(e.target.checked)}
                            className="w-5 h-5 text-emerald-500 rounded border-slate-300 focus:ring-amber-500 focus:ring-offset-1 cursor-pointer"
                          />
                          <label htmlFor="vitalsCompareCheck" className="text-sm font-semibold text-slate-600 flex items-center gap-2 cursor-pointer select-none">
                            <Activity size={16} className="text-emerald-500" /> Group Vitals Comparisons
                          </label>
                        </div>

                        <div className="flex items-center gap-3">
                          <input 
                            type="checkbox" 
                            id="dietCompareCheck"
                            checked={enableCompareDiet}
                            onChange={(e) => setEnableCompareDiet(e.target.checked)}
                            className="w-5 h-5 text-emerald-500 rounded border-slate-300 focus:ring-emerald-500 focus:ring-offset-1 cursor-pointer"
                          />
                          <label htmlFor="dietCompareCheck" className="text-sm font-semibold text-slate-600 flex items-center gap-2 cursor-pointer select-none">
                            {/* You might need to import Utensils from 'lucide-react' at the top */}
                            <Apple size={16} className="text-emerald-500" /> Group Nutrition Comparisons
                          </label>
                        </div>

                        <div className="flex items-center gap-3">
                          <input 
                            type="checkbox" 
                            id="exerciseCompareCheck"
                            checked={enableCompareExercise}
                            onChange={(e) => setEnableCompareExercise(e.target.checked)}
                            className="w-5 h-5 text-emerald-500 rounded border-slate-300 focus:ring-emerald-500 focus:ring-offset-1 cursor-pointer"
                          />
                          <label htmlFor="exerciseCompareCheck" className="text-sm font-semibold text-slate-600 flex items-center gap-2 cursor-pointer select-none">
                            <Dumbbell size={16} className="text-emerald-500" /> Group Exercise Comparisons
                          </label>
                        </div>
                       
                      </div>
                    </div>

                    {/* Input: search members */}
                    <div className="relative">
                      <label className="block text-xs font-bold text-slate-400 uppercase tracking-widest mb-3">Invite Members</label>
                      <div className="relative">
                        <Search className="absolute left-4 top-4 text-slate-400" size={20} />
                        <input 
                          type="text" 
                          placeholder="Search by name..." 
                          value={searchQuery}
                          onChange={(e) => setSearchQuery(e.target.value)}
                          onFocus={() => setIsSearchFocused(true)}
                          onBlur={() => setTimeout(() => setIsSearchFocused(false), 200)}
                          className="w-full bg-slate-50 border border-slate-200 rounded-2xl pl-12 pr-4 py-4 text-slate-700 focus:outline-none focus:ring-2 focus:ring-emerald-500/20 focus:border-emerald-500 transition-all"
                        />
                        {isSearching && <Loader2 className="absolute right-4 top-4 text-emerald-500 animate-spin" size={20} />}
                      </div>

                      {/* Default Recommendations: AI doctor only */}
                      {isSearchFocused && 
                      searchQuery.trim() === '' && 
                      !selectedMembers.some(m => m.uid === aiDoctorUid) && (
                        <div className="mt-2 bg-white rounded-2xl border border-slate-200 shadow-xl divide-y divide-slate-50 overflow-hidden absolute w-full z-20">
                          <div className="bg-slate-50 px-4 py-2 text-[10px] font-bold text-slate-400 uppercase tracking-widest">
                            Recommended
                          </div>
                          {RECOMMENDED_MEMBERS.map(user => (
                            <div 
                              key={user.uid} 
                              className="flex items-center justify-between p-4 hover:bg-slate-50 transition-colors cursor-pointer group/rec"
                              onClick={() => addMember(user)}
                            >
                              <div className="flex items-center gap-3">
                                <div className="w-10 h-10 rounded-full bg-indigo-50 flex items-center justify-center text-indigo-500 overflow-hidden">
                                  {user.imageId ? (
                                    <img 
                                      src={user.imageId} 
                                      alt={user.displayName} 
                                      className="w-full h-full object-cover"
                                    />
                                  ) : (
                                    <Stars size={18} />
                                  )}
                                </div>
                                
                                <div className="flex flex-col">
                                  <span className="font-semibold text-slate-700 group-hover/rec:text-emerald-600 transition-colors">
                                    {user.displayName}
                                  </span>
                                </div>
                              </div>
                              
                              <button className="p-2 bg-emerald-50 text-emerald-600 hover:bg-emerald-500 hover:text-white rounded-full transition-all">
                                <Plus size={20} />
                              </button>
                            </div>
                          ))}
                        </div>
                      )}
                      {/* Search results dropdown */}
                      {searchResults.length > 0 && searchQuery.trim().length >= 2 && (
                        <div className="mt-2 bg-white rounded-2xl border border-slate-200 shadow-xl divide-y divide-slate-50 overflow-hidden absolute w-full z-20">
                          {searchResults.map(user => (
                            <div key={user.uid} className="flex items-center justify-between p-4 hover:bg-slate-50 transition-colors">
                              <div className="flex items-center gap-3">
                                <div 
                                  className="flex items-center gap-3 cursor-pointer group/name"
                                  onClick={() => addMember(user)}
                                >
                                  {user.imageId ? (
                                    <img src={user.imageId} alt="" className="w-10 h-10 rounded-full object-cover bg-slate-100" />
                                  ) : (
                                    <div className="w-10 h-10 rounded-full bg-slate-100 flex items-center justify-center text-slate-400">
                                      <UserIcon size={18} />
                                    </div>
                                  ) }
                                  <span className="font-semibold text-slate-700 group-hover/name:text-emerald-600 transition-colors">{user.displayName}</span>
                                </div>
                              </div>
                              <button 
                                onClick={() => addMember(user)}
                                className="p-2 bg-emerald-50 text-emerald-600 hover:bg-emerald-500 hover:text-white rounded-full transition-all"
                              >
                                <Plus size={20} />
                              </button>
                            </div>
                          ))}
                        </div>
                      )}
                    </div>

                    {/* Selected members list */}
                    {selectedMembers.length > 0 && (
                      <div className="pt-4">
                        <label className="block text-xs font-bold text-slate-400 uppercase tracking-widest mb-4">
                          Selected ({selectedMembers.length})
                        </label>
                        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                          {selectedMembers.map(user => (
                            <div key={user.uid} className="flex items-center justify-between p-3 bg-white border border-slate-100 rounded-xl shadow-sm transition-all hover:border-emerald-100">
                              <div 
                                className="flex items-center gap-3 truncate cursor-pointer group/member-link" 
                                onClick={() => handleProfileClick(user.uid)}
                              >
                                <div className="w-9 h-9 rounded-full bg-emerald-50 flex items-center justify-center text-emerald-600 shrink-0 overflow-hidden">
                                  {user.imageId ? (
                                    <img 
                                      src={user.imageId} 
                                      alt={user.displayName} 
                                      className="w-full h-full object-cover" 
                                    />
                                  ) : (
                                    <div className="font-bold text-xs">
                                      {user.displayName === 'AI Doctor' || user.displayName === 'Personal Trainer' 
                                        ? <Stars size={14}/> 
                                        : user.displayName.charAt(0)}
                                    </div>
                                  )}
                                </div>
                                <span className="font-medium text-slate-700 truncate text-sm">
                                  {user.displayName}
                                </span>
                              </div>
                              <button 
                                onClick={() => removeMember(user.uid)} 
                                className="p-1.5 text-rose-300 hover:text-rose-600 hover:bg-rose-50 rounded-lg transition-colors"
                              >
                                <Minus size={16} />
                              </button>
                            </div>
                          ))}
                        </div>
                      </div>
                    )}
                  </div>

                  <div className="p-6 md:p-8 bg-slate-50/80 border-t border-slate-100">
                    <button 
                      onClick={handleSaveGroup}
                      disabled={!groupName.trim() || selectedMembers.length < 1 || isSaving}
                      className="w-full bg-emerald-500 hover:bg-emerald-600 disabled:bg-slate-300 disabled:cursor-not-allowed disabled:shadow-none text-white font-black py-4 rounded-2xl shadow-lg shadow-emerald-500/20 transition-all flex justify-center items-center gap-2 text-lg active:scale-[0.98]"
                    >
                      {isSaving ? (
                        <Loader2 size={24} className="animate-spin" />
                      ) : !groupName.trim() ? (
                        "Enter Group Name"
                      ) : selectedMembers.length < 1 ? (
                        "Add at least 1 member"
                      ) : (
                        "Create Group"
                      )}
                    </button>
                  </div>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};