// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1jhXYM_1nkOpvkhokcik9_zYSrSenRRM',
    appId: '1:702841156351:web:b105027698de92b56d52ca',
    messagingSenderId: '702841156351',
    projectId: 'squarehexagon-holdings',
    authDomain: 'squarehexagon-holdings.firebaseapp.com',
    storageBucket: 'squarehexagon-holdings.firebasestorage.app',
    measurementId: 'G-QV7Q6LZZHJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIoPm-MUXFF4SCqvxpXrCcRpuTflX3rT4',
    appId: '1:702841156351:android:56f027565811e10c6d52ca',
    messagingSenderId: '702841156351',
    projectId: 'squarehexagon-holdings',
    storageBucket: 'squarehexagon-holdings.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_D2XesqDyoDbLEUhxjlwFxuTOb5I7rlI',
    appId: '1:702841156351:ios:e09312dd47f8c8f56d52ca',
    messagingSenderId: '702841156351',
    projectId: 'squarehexagon-holdings',
    storageBucket: 'squarehexagon-holdings.firebasestorage.app',
    iosClientId: '702841156351-7ung6bv6kd2c7u66te8ac67mog4graq5.apps.googleusercontent.com',
    iosBundleId: 'com.example.myHealthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_D2XesqDyoDbLEUhxjlwFxuTOb5I7rlI',
    appId: '1:702841156351:ios:e09312dd47f8c8f56d52ca',
    messagingSenderId: '702841156351',
    projectId: 'squarehexagon-holdings',
    storageBucket: 'squarehexagon-holdings.firebasestorage.app',
    iosClientId: '702841156351-7ung6bv6kd2c7u66te8ac67mog4graq5.apps.googleusercontent.com',
    iosBundleId: 'com.example.myHealthApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1jhXYM_1nkOpvkhokcik9_zYSrSenRRM',
    appId: '1:702841156351:web:77e0675bc869bda96d52ca',
    messagingSenderId: '702841156351',
    projectId: 'squarehexagon-holdings',
    authDomain: 'squarehexagon-holdings.firebaseapp.com',
    storageBucket: 'squarehexagon-holdings.firebasestorage.app',
    measurementId: 'G-KX84FV33NX',
  );
}
